name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - id: package
        name: Extract package info
        run: |
          VERSION=$(jq -r .version package.json)
          MAJOR_MINOR=$(jq -r '.version | split(".") | .[:2] | join(".")' package.json)
          MAJOR=$(jq -r '.version | split(".") | first' package.json)
          echo "::set-output name=build_version::${VERSION}"
          echo "::set-output name=version::v${VERSION}"
          echo "::set-output name=major_minor::v${MAJOR_MINOR}"
          echo "::set-output name=major::v${MAJOR}"

      - uses: actions/github-script@v4
        name: Create version release
        id: release
        env:
          VERSION: ${{ steps.package.outputs.version }}
          COMMIT: ${{ github.sha }}
        with:
          script: |
            try {
              await github.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: process.env.VERSION,
                target_commitish: process.env.COMMIT,
              })
              core.setOutput('created', 'yes')
            }
            catch (error) {
              if (error.status === 422) {
                core.setOutput('created', 'no')
              }
              else {
                throw error
              }
            }

      - name: Set up QEMU
        if: steps.release.outputs.created == 'yes'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: steps.release.outputs.created == 'yes'
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        if: steps.release.outputs.created == 'yes'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: steps.release.outputs.created == 'yes'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.package.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ steps.package.outputs.major_minor }}
            ghcr.io/${{ github.repository }}:${{ steps.package.outputs.major }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.package.outputs.build_version }}
