name: Build

on:
  release:
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types: [completed]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - id: details
        name: Extract package info
        env:
          IMAGE_REPO: ghcr.io/${{ github.repository }}
          TAGS: ghcr.io/${{ github.repository }}:latest
          REF: ${{ github.ref }}
        run: |
          for tag in $(echo "$REF" | jq -R -r 'scan("refs\\/tags\\/(.+)") | map(split(".") as $parts | reduce range($parts | length) as $n ([]; . + [$parts[:$n+1] | join(".")])) | flatten | .[]'); do
            printf -v TAGS "${TAGS}\n${IMAGE_REPO}:${tag}"
          done
          VERSION=$(jq -r .version package.json)
          echo "::set-output name=tags::${TAGS}"
          echo "::set-output name=version::${VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.details.outputs.tags }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.details.outputs.version }}
