name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - id: package
        name: Extract package info
        run: |
          VERSION=$(jq -r .version package.json)
          MAJOR_MINOR=$(jq -r '.version | split(".") | .[:2] | join(".")' package.json)
          MAJOR=$(jq -r '.version | split(".") | first' package.json)
          echo "::set-output name=version::v${VERSION}"
          echo "::set-output name=major_minor::v${MAJOR_MINOR}"
          echo "::set-output name=major::v${MAJOR}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.package.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ steps.package.outputs.major_minor }}
            ghcr.io/${{ github.repository }}:${{ steps.package.outputs.major }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
